# build environment
FROM node:15.14 as builder
RUN mkdir /usr/src/app
WORKDIR /usr/src/app
ENV PATH /usr/src/app/node_modules/.bin:$PATH
ADD package.json /usr/src/app/package.json
RUN npm install --silent
# RUN npm install react-scripts@3.4.4 -g --silent
ADD . /usr/src/app
RUN npm run build

# production environment
FROM nginx:1.13.5-alpine
RUN rm -rf /etc/nginx/conf.d
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=builder /usr/src/app/build /usr/share/nginx/html/frontend
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
